version: '2.1'
services:
  vinyl:
    build:
      context: .
      dockerfile: docker/vinyl/Dockerfile
    ports:
      - 8080:8080
    env_file: ./env/.test.env
    environment:
      HOST: docker
    depends_on: [turntable]

  turntable:
    build:
      context: .
      dockerfile: docker/turntable/Dockerfile
    depends_on: [prisma]
    env_file: ./env/.test.env
    ports:
      - 9000:9000

  #TODO: Add healthcheck
  prisma:
    image: prismagraphql/prisma:1.15
    restart: unless-stopped
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    ports:
      - 4466:4466
    depends_on: [postgres]

  #TODO: Add healthcheck
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma

  chrome-headless:
    image: openrecord/chrome-headless
    build:
      dockerfile: docker/chrome-headless/Dockerfile
      context: .
    ports:
      - 9223:9223
