[build]
  functions = "./turntable/dist/functions"
  command = "npm run build"
  environment = { ENDPOINT = "http://localhost:4466/" }

[context.production]
  environment = { ENDPOINT = "https://us1.prisma.sh/jamesscottmcnamara/turntable/dev" }

[context.develop]
  environment = { ENDPOINT = "https://us1.prisma.sh/jamesscottmcnamara/turntable/staging" }

[context.deploy-preview]
  environment = { ENDPOINT = "https://us1.prisma.sh/jamesscottmcnamara/turntable/staging" }