version: 2
jobs:
  build:
    docker:
      - image: videoblocks/circleci-docker-base:latest

    steps:
      - setup_remote_docker: # try to allow docker layer caching: https://circleci.com/docs/2.0/docker-layer-caching/
          reusable: true
          exclusive: true

      - checkout

      - run:
          name: Start postgres, prisma server, and chrome-headless.
          command: docker-compose -f docker-compose.test.yml up --build -d prisma chrome-headless

      - run:
          name: Build test images.
          command: docker-compose -f docker-compose.test.yml build turntable vinyl

      - run:
          name: Take a nap
          command: sleep 10

      - run:
          name: Start turntable server
          command: docker-compose -f docker-compose.test.yml up -d turntable

      - run:
          name: Start vinyl container
          command: docker-compose -f docker-compose.test.yml up -d vinyl

      - run:
          name: Take longer a nap
          command: sleep 30

      - run:
          name: Peek at turntable logs
          command: docker-compose -f docker-compose.test.yml logs turntable

      - run:
          name: Run end-to-end tests in a new vinyl container.
          command: |
            docker rm test-run || echo "Test contaner does not exist."
            docker-compose -f docker-compose.test.yml run --name test-run vinyl npm run test:ci

      - run:
          name: Peek at all logs
          command: docker-compose -f docker-compose.test.yml logs

      - run:
          name: Copy test artifacts from the test-run container into the job space.
          when: always
          command: |
            docker cp test-run:/app/test-screenshots .
            docker cp test-run:/app/test-reports .

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_artifacts:
          path: test-screenshots
          destination: test-screenshots
